spring:
  application:
    name: zipkin-service
  datasource:
    schema: classpath:/mysql.sql
  cloud:
    services:
      registrationMethod: route
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql
management:
  security:
    enabled: false
eureka:
  instance:
     nonSecurePort: 80
security:
  basic:
    enabled: false